server:
  port: 8083
spring:
  application:
    name: search-service
  #main:
      #allow-bean-definition-overriding: true # 不添加，较新版本发的SpringBoot注释相同的@FeignClient(value = "item-service")报错
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.43.141:9300
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  rabbitmq:
    host: 192.168.43.141
    username: democloud
    password: demo376DC
    virtual-host: /democloud
eureka:
  client:
    registry-fetch-interval-seconds: 10 # 备份服务列表到本地缓存的周期，生产环境不需要设置（默认30s）
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳，生产环境不需要设置（默认30s）
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期，生产环境不需要设置（默认90s）
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
## 高版本feign, 需要开启才能处理熔断
feign:
  hystrix:
    enabled: true # 高版本需要开启才能处理熔断
## 负载均衡策略需要指定服务(serviceId)才能生效
item-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
## 负载均衡超时设置等可以不指定服务(serviceId)
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 1000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
## 熔断超时时长设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 2000ms