server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    registry-fetch-interval-seconds: 10 # 备份服务列表到本地缓存的周期，生产环境不需要设置（默认30s）
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳，生产环境不需要设置（默认30s）
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期，生产环境不需要设置（默认90s）
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true # 高版本需要开启才能处理熔断
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 2000 # 连接超时时间(ms)
    ReadTimeout: 2000 # 通信超时时间(ms)
    OkToRetryOnAllOperations: true # 是否对所有操作重试
    MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
    MaxAutoRetries: 1 # 同一实例的重试次数
dc:
  jwt:
    secret: hhh@123.com&xlli% # 登录校验的密钥
    pubKeyPath: D:/jwt/rsa/rsa.pub # 公钥地址
    priKeyPath: D:/jwt/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: DC_TOKEN # cookie名称
    cookieMaxAge: 1800 # cookie过期时间
logging:
  level:
    com.cloud.demo.auth.service.feign: DEBUG
